config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  resources :articles do
    member do
      post :contact
    end
  end

  get 'my_articles' => 'articles#my_articles'

  resources :password, only: [] do
    get 'edit', on: :collection
    patch 'update', on: :collection
  end

  resources :pages, only:[] do
    collection do
      get :terms
      get :policies
    end
  end

  resources :favorites, only: [:create, :destroy]
  get 'my_favorites' => 'favorites#my_favorites'

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  name        :string(100)      not null
#  description :text             not null
#  location    :string           not null
#  status      :integer
#  offer_type  :integer          not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  slug        :string
#
# Indexes
#
#  index_articles_on_category_id  (category_id)
#  index_articles_on_slug         (slug) UNIQUE
#  index_articles_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  belongs_to :category, optional: true
  has_many :favorites, as: :favorited, dependent: :destroy
  has_many :article_images, dependent: :destroy

  validates :name, :description, :offer_type, :location, :user, presence: true
  validates_length_of :name, maximum: 100

  enum offer_type: [:gift, :barter]
  enum status: [:reserved, :available, :disabled]

  scope :pusblish_articles, -> { where(status: :available) }

  after_initialize :default_values

  accepts_nested_attributes_for :article_images, reject_if: :all_blank, allow_destroy: true

  def image_main
    article_images&.first
  end

  def image_main_url
    image_main&.image_file_name&.url
  end

  def total_images
    images_number = self.article_images.count
    (5 - images_number).times { self.article_images.build }
  end

  def user_email
    user.email
  end

  private

  def default_values
    self.status ||= Article.statuses[:available]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only:[:show, :edit, :contact, :update]

  def index
    @articles = Article.pusblish_articles
  end

  def my_articles
    @gifts = current_user.articles.find_all { |a| a.gift? }
    @barters = current_user.articles.find_all { |a| a.barter? }
  end

  def show
  end

  def new
    @article = Article.new
    5.times { @article.article_images.build }
    render :form
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      flash[:notice] = "Se ha agregado un nuevo articulo"
      redirect_to my_articles_path
    else
      flash[:notice] = @article.errors.full_messages.first
      5.times { @article.article_images.build }
      render 'form'
    end
  end

  def edit
    @article.total_images
    render :form
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Se ha modificado el  articulo #{@article.name}"
      redirect_to my_articles_path
    else
      flash[:notice] = @article.errors.full_messages.first
      @article.total_images
      render :form
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = "Se ha eliminado el  articulo #{@article.name}"
    else
      flash[:notice] = "no se pudo eliminar articulo #{@article.name}"
    end

    redirect_to my_articles_path
  end

  def contact
    ArticlesMailer.contact(@article, current_user).deliver_now
  end


  private
  def article_params
    params.require(:article).permit(
      :name, :offer_type, :description, :status, :photo, :location,
      article_images_attributes:[:id, :image_file_name, :_destroy]
    )
  end

  def set_article
    @article = Article.friendly.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def display_article_user(user)
    if user.name.present?
      user.name
    elsif user.email.present?
      display_email(user)
    else
      display_phone(user)
    end
  end

  def display_phone(user)
    user_signed_in? ? user.phone : user.phone.sub(/^.../, '*****')
  end

  def display_email(user)
    user_signed_in? ? user.email : user.email.split('@')[0]
  end
end

app/views/articles/contact.js.erb
swal(
  '¡se ha enviado su solicitud de contacto!',
  'Debes iniciar sesión para contactar el usuario de este artículo',
  'success'
)

app/views/articles/form.html.erb
<div class="container">
  <div class="row">
    <div class='col-md-12'>
      <div class='back-link'>
        <%= link_to '<i class="fa fa-arrow-circle-left" aria-hidden="true"></i> Volver Atrás'.html_safe, :back %>
      </div>
      <div class="panel-heading">
        <h4><%= @article.new_record?  ? 'Publicar artículo' : 'Editar Articulo' %></h4>
        <hr>
      </div>
    </div>
  </div>

  <%= form_for @article, multipart: true do |f| %>
    <div class="row">
      <div class='col-md-6 add-articles'>
        <h4>Subir Imágenes</h4>
        <div class="row text-center">
          <%= f.nested_fields_for :article_images, wrapper_tag: :div do |ff| %>
            <%= render partial: 'articles/shared/article_image_field', locals: {ff: ff }%>
          <% end %>

          <%= f.add_nested_fields_link :article_images, '', class: 'hidden' %>
        </div>
      </div>

      <div class='col-md-6'>
        <h4>Información Básica</h4>
        <div class="form-group">
          <%= f.text_field :name, autofocus: true, class: "form-control", placeholder: "Nombre del articulo" %>
        </div>
        <div class="form-group">
          <%= f.select :offer_type, generate_list(Article.offer_types) , { include_blank: 'Tipo' },  { class: 'form-control' }  %>
        </div>

        <div class="form-group">
          <%= f.select :location, region_country, { include_blank: "Ciudad" },  { class: 'form-control' }  %>
        </div>

        <div class="form-group">
          <%= f.text_area :description, class: "form-control", placeholder: "Descripción" %>
        </div>

        <% if @article.new_record? %>
          <div class="form-group accepted-terms">
            <%= radio_button_tag :status, false %>
            Estoy seguro que mi articulo publicado cumple con los <%= link_to 'Términos y Condiciones de llevatelo.co','#', data:{toggle: "modal", target: "#termsModal" } %>
            <br/>
            <label id="status-error" class="error" for="status"></label>
          </div>
        <% end %>
      </div>

      <div class="text-center">
        <%= f.button "Guardar", class: "btn-lg btn btn-primary"  %>
      </div>
    </div><!-- end row-->
  <% end %>
</div>

<%= render 'articles/shared/preview_image_modal' %>
<%= render 'shared/terms_modal' %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h2>Últimos Artículos</h2>
      <div class="row">
        <% @articles.each_slice(4) do |articles| %>
          <div class="row text-center">
            <% articles.each do |article| %>
              <%= render 'shared/article', { article: article } %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/articles/my_articles.html.erb
<div class="container my-articles">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-login">
        <div class="panel-heading">
          <%= render 'shared/menu_dashboard' %>
          <hr>
        </div>
        <div class="panel-body">
          <div class="row">
            <div class="col-lg-12 col-md-12 col-xs-12">
              <div class="articles-tabs">
                <ul class="nav nav-tabs">
              		<li class="active"><a  href="#1" data-toggle="tab">Regalo</a></li>
              		<li><a href="#2" data-toggle="tab">Cambios</a></li>
                </ul>
            		<div class="tab-content ">
            		  <div class="tab-pane active" id="1">
                    <%= render partial: 'articles/shared/article_table', locals: { articles: @gifts, editable: true } %>
            			</div>

                  <div class="tab-pane" id="2">
                    <%= render  partial: 'articles/shared/article_table', locals: { articles: @trades, editable: true }  %>
            			</div>
            		</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<!-- app/views/offers/show.html.erb -->
<% content_for :meta_title, "#{@article.name} en #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @article.description %>
<% if @article.image_main.present? %>
  <% content_for :meta_image, @article.image_main_url %>
<% end %>

<section class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="row" id="productMain">
          <%= render 'articles/shared/images' %>
          <div class="col-sm-6">
            <div class="description-article">
              <div class="sizes">
                <h3><%= @article.name %></h3>
                <%= badge_offer_type_button(@article.offer_type) %><br/>
                <span class="time-ago">
                  <i class="fa fa-clock-o"></i> <%= time_ago_in_words(@article.updated_at) %>
                </span>
                </br>

                <span class="time-ago">
                  <i class="fa fa-map-marker" aria-hidden="true"></i> <%= @article.location %>
                </span>
              </div>

              <% unless @article.user == current_user %>
                <div class="text-center actions">
                  <% if user_signed_in? %>
                    <%= link_to '<i class="fa fa-address-book-o"></i> Contactar'.html_safe, contact_article_path(@article),remote: true, method: :post, data: {
                      confirm: '¿Esta seguro que lo quieres contactar?',
                        'confirm-button-color': '#ff7473',
                        'confirm-button-text': '¡Si, estoy seguro!',
                        'cancel-button-text': 'Cancelar'
                      }, class: 'btn btn-info' %>
                  <% else %>
                    <%= link_to '<i class="fa fa-address-book-o"></i> Contactar'.html_safe, '#', id:'contactWithoutSignIn', class: 'btn btn-info' %>
                  <% end %>
                  <%= favorited_button(@article) %>
                </div>
              <% end %>
              <div class="text-center">
                <a class="scroll-to" href="#details">Ver Descripción</a>
              </div>
            </div>
            <hr/>

            <div class="row" id="thumbs">
              <div class="jumbotron">
                <p><b>Llevatelo.co</b> NO participa en ninguna negociación,
                  Sólo se limita a la publicación de los artículos de sus usuarios.
                </p>
              </div>
            </div>
          </div>
        </div><!-- end productMain-->
        <hr/>
        <div id="details">
          <p>
            <h4>Descripción</h4>
          <p><%= @article.description %></p>
        </div>
        <div class="social" id="product-social">
          <h4>Compartir</h4>
          <p>
            <a href="https://www.facebook.com/sharer/sharer.php?u=<%= article_url(@article) %>"
            class="share facebook" data-network="facebook" data-animate-hover="pulse" style="opacity: 1;">
              <i class="fa fa-facebook"></i>
            </a>

            <a href="https://twitter.com/share?url=<%= article_url(@article) %>"
              class="share twitter" data-network="twitter" data-animate-hover="pulse" style="opacity: 1;">
              <i class="fa fa-twitter"></i>
            </a>

             <a href="https://wa.me/?text=<%= article_url(@article) %>"
              class="share whatsapp" data-network="whatsapp" data-animate-hover="pulse" style="opacity: 1;">
              <i class="fa fa-whatsapp"></i>
            </a>
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end section -->


<script>
  $('a.share').click(function(e){
    e.preventDefault();
    var $link   = $(this);
    var href    = $link.attr('href');
    var network = $link.attr('data-network');

    var networks = {
        facebook : { width : 600, height : 300 },
        twitter  : { width : 600, height : 254 },
        whatsapp : { width : 515, height : 490 },
    };

    var popup = function(network){
        var options = 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,';
        window.open(href, '', options+'height='+networks[network].height+',width='+networks[network].width);
    }

    popup(network);
});
</script>