config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  resources :articles do
    member do
      post :contact
    end
  end

  get 'my_articles' => 'articles#my_articles'

  resources :password, only: [] do
    get 'edit', on: :collection
    patch 'update', on: :collection
  end

  resources :pages, only:[] do
    collection do
      get :terms
      get :policies
    end
  end

  resources :favorites, only: [:create, :destroy]
  get 'my_favorites' => 'favorites#my_favorites'

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  layout 'landing'

  def index
    @articles = Article.pusblish_articles.limit(8)
  end
end

app/views/landing/shared/_banner.html.erb
<section id="intro" class="text-intro no-padding-bottom">
  <div class="dark-mask"></div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1> ¿TIENES ALGO QUE NECESITES? ¿ALGO QUE DESEES REGALAR O INTERCAMBIAR?</h1>
        <h3 class="weight-300">Comparte aquellas cosas que ya no usas, puedes deshacerte de las cosas que no utilices y/o encuentra algo que te guste o necesite</h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= link_to 'Comenzar Ahora', new_user_registration_path, class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
</section>

app/views/landing/shared/_contact_form.html.erb
<section id="contact" class="section background-gray-lightest">
  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-2">
        <div class="box-simple">
          <div class="icon"><i class="fa fa-mobile"></i></div>
          <h3>WhatsApp/Número celular</h3>
          <p class="text-muted">¿Tienes preguntas? Llámanos o escríbenos.</p>
          <p><strong><a href="http://api.whatsapp.com/send?phone=573015692996" target='_blank'>+57 3015692996</a></strong></p>
        </div>
      </div>
      <div class="col-md-4">
        <div class="box-simple">
          <div class="icon"><i class="fa fa-envelope-o"></i></div>
          <h3>Correo electrónico</h3>
          <p class="text-muted">No dudes en contactarnos vía e-mail si tienes dudas o sugerencias, Nos dará gusto responder todas sus inquietudes.</p>
          <p><strong><a href="mailto:">nmena.garzon@gmail.com</a></strong></p>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/landing/shared/_features.html.erb
<section id="features"  class="section">
  <div class="container">
    <div class="row text-center">
      <h2>Características</h2>
    </div>

    <div class="col-lg-4">
      <div class="text-center">
        <span class="fa fa-handshake-o fa-4x"></span>
      </div>
      <h2 class="text-center">Intercambia</h2>
      <p>¿No sabes qué hacer con ese articulo que ya no usas? Publícala e intercámbiala por algo que te guste.</p>
      <br><br>
      <p>Da clic en <b><a href="">CAMBIO</a></b> y revisa tus ofertas.</p>
    </div>

    <div class="col-lg-4 callout">
      <div class="text-center">
        <span class="fa fa-gift  fa-4x"></span>
      </div>
      <h2 class="text-center">Regala</h2>
      <p>¿Tienes cosas en buen estado que te da lástima botar? ¿Por qué no las regalas?</p>
      <p>Registra esos objetos y dales una segunda oportunidad de ser útiles.</p>
      <p>Da clic en <b><a href="">REGALA</a></b> e ingresa tus objetos.</p>
    </div>

    <div class="col-lg-4 callout">
      <div class="text-center">
        <span class="fa fa-hand-lizard-o  fa-4x"></span>
      </div>
      <h2 class="text-center">Solicita</h2>
      <p>Andas buscando algo pero no puedes comprarlo, Solicitalo y encuentra a alguien que lo posea y te lo quiera regalar.</p>
      <br><br>
      <p>Da clic en <b><a href="">NECESITO</a></b>, y encuentra lo que buscas sin gastar dinero.</p>
   </div>
  </div>
</section>

app/views/landing/shared/_list_articles.html.erb
<section id="articles" class="section background-gray-lightest">
  <div class="container">
    <div class="row text-center">
      <h2>Últimos Artículos </h2>
      <% @articles.each_slice(4) do |articles| %>
        <div class="row text-center">
          <% articles.each do |article| %>
            <%= render 'shared/article', { article: article } %>
          <% end %>
        </div>
      <% end %>

      <div class="row text-center">
        <div class="col-md-12">
          <%= link_to 'Ver Mas artículos', articles_path, class: 'btn btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/landing/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <a class ='navbar-brand scroll-to' href="#all">
        <i class='icon-logo'></i> llevatelo
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a class ="link scroll-to" href="#features">Características</a></li>
        <li><a class ="link scroll-to"  href="#contact">Contacto</a></li>
        <li><a  href='<%= new_user_session_path %>' class="btn navbar-btn btn-ghost btn-sign-in">Ingresar</a></li>
        <li><%= link_to '<i class="glyphicon glyphicon-plus"></i> Publicar artículo'.html_safe, new_article_path, class: 'btn navbar-btn btn-ghost btn-started' %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>