config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  resources :articles do
    member do
      post :contact
    end
  end

  get 'my_articles' => 'articles#my_articles'

  resources :password, only: [] do
    get 'edit', on: :collection
    patch 'update', on: :collection
  end

  resources :pages, only:[] do
    collection do
      get :terms
      get :policies
    end
  end

  resources :favorites, only: [:create, :destroy]
  get 'my_favorites' => 'favorites#my_favorites'

end

app/views/shared/_article.html.erb
<div class="col-md-3 col-sm-6 hero-article">
  <div class="thumbnail">
    <h4 class="article-heading"><%= truncate(article.name, length: 25) %></h4>
    <div class = "image-article" style="background-image: url(<%= display_image_article(article) %>);"></div>
    <%= badge_offer_type_button(article.offer_type) %>
    <div class="caption">
      <p>
        <a class="asset-link-location"><%= article.location %></a><br/>
        <%= link_to 'Mas Info',article_path(article), class: 'btn btn-default' %>
      </p>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="footer__copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-3">
          <p>Llevatelo.co es creado por:<br/><b>Nicolas Mena</b></p>
        </div>

        <div class="col-md-3">
          <p><%= link_to 'Términos y Condiciones', terms_pages_path %></p>
          <p><%= link_to 'Políticas de uso', policies_pages_path %></p>
        </div>

        <div class="col-md-3">
          <strong>¡SÍGUENOS!</strong>
          <ul>
            <a href='https://www.facebook.com/llevatelonm/' target='_blank'>
              <i class='fa fa-facebook-square' style='font-size:24px;'></i>
            </a>
            <a href='#'>
              <i class='fa fa-instagram' style='font-size:24px'></i>
            </a>
          </ul>
        </div>

        <div class="col-md-3">
          <!-- Not removing these links is part of the license conditions of the template. Thanks for understanding :) If you want to use the template without the attribution links, you can do so after supporting further themes development at https://bootstrapious.com/donate  -->
          <p class="credit pull-right">Code by <a href="https://bootstrapious.com/landing-pages" class="external">Bootstrapious</a></p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_google_tag.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-111616420-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){
    dataLayer.push(arguments);
  }
  gtag('js', new Date());

  gtag('config', 'UA-111616420-1');
</script>

app/views/shared/_list_navigation.html.erb
<ul class="nav navbar-nav navbar-right">
  <% if user_signed_in? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-user" aria-hidden="true"></i> Mi Perfil <span class="caret"></span>
      </a>
      <ul class="dropdown-menu">
        <li>
          <%= link_to '<i class="fa fa-hand-pointer-o"></i> Mis Publicaciones'.html_safe,  my_articles_path %>
        </li>
        <li>
          <%= link_to '<i class="fa fa-heart"></i> Mis Favoritos'.html_safe, my_favorites_path %>
        </li>

        <li>
          <%= link_to '<i class="fa fa-id-badge"></i> Editar Perfil'.html_safe, edit_user_registration_path %>
        </li>
        <li role="separator" class="divider"></li>
        <li>
          <%= link_to '<i class="fa fa-sign-out"></i> Salir'.html_safe, destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  <% else %>
    <li>
      <%= link_to 'Ingresar/Registrarse', new_user_session_path, class: 'btn navbar-btn btn-ghost btn-sign-in' %>
    </li>
  <% end %>

  <li  class="page-scroll sign-in">
    <%= link_to '<i class="glyphicon glyphicon-plus"></i> Publicar artículo'.html_safe, new_article_path, class: 'btn navbar-btn btn-ghost btn-started' %>
  </li>
</ul>

app/views/shared/_menu_dashboard.html.erb
<ul class="nav nav-pills">
  <li role="presentation" class="<%= active_nav(my_articles_path) %>">
    <%= link_to 'Mis publicaciones', my_articles_path  %>
  </li>
  <li role="presentation" class="<%= active_nav(my_favorites_path) %>">
    <%= link_to 'Mis Favoritos', my_favorites_path  %>
  </li>
  <li role="presentation" class="<%= active_nav(edit_user_registration_path) %>">
    <%= link_to 'Mi Perfil', edit_user_registration_path %>
  </li>
</ul>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to '<i class="icon-logo"></i> llevatelo'.html_safe, root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= render 'shared/list_navigation' %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_polices.html.erb
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="policesmodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Política de privacidad</h4>
      </div>
      <div class="modal-body">
        <p>En <b>Llevatelo.co</b> respetamos tu  información que recolectamos y la guardamos muy bien. Ningún tipo de información personal será vendida ni intercambiada con terceros.</p>
        <h2>Publicación de productos.</h2>
        <p>Los elementos  publicados junto con la información en <b>llevatelo.co</b> son almacenadas y se hacen públicamente visibles hasta que se llegue a un acuerdo con otro usuario o se decida eliminar la publicación, luego del cual no podrá ser accedida nuevamente.</p>
        <h2>Recibir ofertas</h2>
        <p><b>Llevatelo.co</b> solo almacena información que haga referencia a los productos publicados y que permitan llevar a cabo las trnsacciones. No almacena nombres, documentos, direcciones o cualquier información de carácter personal que pueda ser utilizada para identificar a una persona.</p>
        <h2>En general</h2>
        <p>Cumplimos con el Hábeas Data de la legislación de Colombia.</p>
        <p>Mantenemos los datos almacenados de forma segura y damos un manejo responsable de los mismos.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<form id="search-form" method="get" action="#" class="search-form">
  <div class="controls">
    <div class="row">
      <div class="col-sm-5">
        <div class="form-group">
          <label for="profession">Articulo</label>
          <input type="text" id="article" name="article" placeholder="Articulo que estas buscando" class="form-control">
        </div>
      </div>
      <div class="col-sm-2">
        <button type="submit" name="submit" class="btn btn-primary"><i class="fa fa-search"></i> Buscar</button>
      </div>
    </div>
  </div>
</form>

app/views/shared/_terms_modal.html.erb
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="termsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Terminos y Condiciones</h4>
      </div>
      <div class="modal-body">
        <p>Al ingresar información en esta plataforma estas aceptando, de manera expresa, libre y voluntaria las siguientes condiciones para el tratamiento de sus datos personales.
        Ningún tipo de información personal será vendida.</p>

        <h2>Publicación de productos.</h2>
        <p>La información requerida se utilizará para:</p>

        <ol>
          <li>Ofertar un producto como regalo o trueque  disponible para cualquier visitante de <b>llevatelo.co</b> este estará disponible hasta que se concrete la transacción.</li>
          <li>Solicitar un producto bien sea como regalo o trueque, dicha solicitud podrá ser  vista por cualquier visitante de Llevatelo.co.</li>
          <li>Compartir la oferta del producto de manera publica por email, redes sociales, u otros medios que permitan su difusión masiva.
          <li>Establecer a <b>Llevatelo.co</b>  como un canal de comunicación  entre el publicante y aquellas personas interesadas en las ofertas.</li>
        </ol>


        <h2>Que no puedes ofertar. </h2>

        <ol>
          <li>En <b>Llevatelo.co</b> no se permite la publicación de ningún tipo de animal o ser vivo.</li>
          <li>Igualmente <b>llevatelo.co</b> no permite que se publiquen artículos prohibidos por las normas leyes vigentes del país donde se haga uso de la aplicación, por lo no se hace responsable por las transacciones de aquellos productos que no cumplan con la ley.</li>
          <li> <b>Llevatelo.co</b> es una plataforma gratuita y no se permite el uso de dinero como intercambio a otros productos en la plataforma, salvo sea moneda coleccionable.</li>
        </ol>


        <h2>En General</h2>

        <p>Al navegar y registrarte a <b>Llevatelo.co</b>  reconoces y aceptas que tus datos aquí registrados podrán ser puestos a disposición del personal encargado dentro de la compañía con el fin de cumplir las  finalidades citadas.
          Además  reconoces y aceptas que te hemos informado plena y suficientemente mente acerca de tus derechos como titular de los datos registrados en <b>Llevatelo.co</b>, y declaras, reconoces y aceptas que la información suministrada de forma voluntaria, en el momento del registro,  publicación y oferta  es verídica y que no se ha omitido o adulterado ninguna información.
          <b>Llevatelo.co</b> es solo un intermediario y no participa en ninguna transacción entre usuarios, y no se hace responsable por lo aquí publicado.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>