config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  devise_for :users, :controllers => { registrations: 'users/registrations', confirmations: 'users/confirmations' }
  resources :articles do
    member do
      post :contact
    end
  end

  get 'my_articles' => 'articles#my_articles'

  resources :password, only: [] do
    get 'edit', on: :collection
    patch 'update', on: :collection
  end

  resources :pages, only:[] do
    collection do
      get :terms
      get :policies
    end
  end

  resources :favorites, only: [:create, :destroy]
  get 'my_favorites' => 'favorites#my_favorites'

end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id          :integer          not null, primary key
#  name        :string(100)      not null
#  description :text             not null
#  location    :string           not null
#  status      :integer
#  offer_type  :integer          not null
#  user_id     :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  category_id :integer
#  slug        :string
#
# Indexes
#
#  index_articles_on_category_id  (category_id)
#  index_articles_on_slug         (slug) UNIQUE
#  index_articles_on_user_id      (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (category_id => categories.id)
#  fk_rails_...  (user_id => users.id)
#

class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  belongs_to :user
  belongs_to :category, optional: true
  has_many :favorites, as: :favorited, dependent: :destroy
  has_many :article_images, dependent: :destroy

  validates :name, :description, :offer_type, :location, :user, presence: true
  validates_length_of :name, maximum: 100

  enum offer_type: [:gift, :barter]
  enum status: [:reserved, :available, :disabled]

  scope :pusblish_articles, -> { where(status: :available) }

  after_initialize :default_values

  accepts_nested_attributes_for :article_images, reject_if: :all_blank, allow_destroy: true

  def image_main
    article_images&.first
  end

  def image_main_url
    image_main&.image_file_name&.url
  end

  def total_images
    images_number = self.article_images.count
    (5 - images_number).times { self.article_images.build }
  end

  def user_email
    user.email
  end

  private

  def default_values
    self.status ||= Article.statuses[:available]
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only:[:show, :edit, :contact, :update]

  def index
    @articles = Article.pusblish_articles
  end

  def my_articles
    @gifts = current_user.articles.find_all { |a| a.gift? }
    @barters = current_user.articles.find_all { |a| a.barter? }
  end

  def show
  end

  def new
    @article = Article.new
    5.times { @article.article_images.build }
    render :form
  end

  def create
    @article = current_user.articles.new(article_params)

    if @article.save
      flash[:notice] = "Se ha agregado un nuevo articulo"
      redirect_to my_articles_path
    else
      flash[:notice] = @article.errors.full_messages.first
      5.times { @article.article_images.build }
      render 'form'
    end
  end

  def edit
    @article.total_images
    render :form
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Se ha modificado el  articulo #{@article.name}"
      redirect_to my_articles_path
    else
      flash[:notice] = @article.errors.full_messages.first
      @article.total_images
      render :form
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      flash[:notice] = "Se ha eliminado el  articulo #{@article.name}"
    else
      flash[:notice] = "no se pudo eliminar articulo #{@article.name}"
    end

    redirect_to my_articles_path
  end

  def contact
    ArticlesMailer.contact(@article, current_user).deliver_now
  end


  private
  def article_params
    params.require(:article).permit(
      :name, :offer_type, :description, :status, :photo, :location,
      article_images_attributes:[:id, :image_file_name, :_destroy]
    )
  end

  def set_article
    @article = Article.friendly.find(params[:id])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def display_article_user(user)
    if user.name.present?
      user.name
    elsif user.email.present?
      display_email(user)
    else
      display_phone(user)
    end
  end

  def display_phone(user)
    user_signed_in? ? user.phone : user.phone.sub(/^.../, '*****')
  end

  def display_email(user)
    user_signed_in? ? user.email : user.email.split('@')[0]
  end
end

app/views/articles/shared/_article_image_field.html.erb
<div class="col-md-4 col-sm-6">
  <div class="thumbnail">
    <div class="img-content">
      <% if ff.object.new_record? %>
        <div class="js-image-preview"></div>
      <% else %>
        <div class="js-image-preview" style="background-image: url('<%= ff.object.image_file_name_url %>');"></div>
      <% end %>
    </div>

    <div class='actions'>
      <a class="preview-image btn btn-default btn-xs" href="#" data-toggle="tooltip" data-placement="bottom" title="Ver">
        <i class="glyphicon glyphicon-eye-open"></i>
      </a>
      <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, '#', class: 'destroy-article btn btn-danger btn-xs' %>
      <%= ff.remove_nested_fields_link '', class: 'hidden' %>
    </div>


    <%= ff.file_field :image_file_name, class: 'hidden file-image' %>
  </div>
</div>

app/views/articles/shared/_article_table.html.erb
<div class="articles-listing">
  <% if articles.present? %>
    <table class="table table-striped table-bordered table-list">
      <thead>
        <tr>
          <th></th>
          <th>Nombre</th>
          <th>Descripción</th>
          <% if editable %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% articles.each do |article| %>
          <tr>
            <td><%= image_tag(display_image_article(article), class: 'img-responsive image-small') %></td>
            <td><%= link_to article.name, article_path(article) %></td>
            <td><p style='width: 90%;'>
              <%= article.description %></p>

            </td>
            <% if editable %>
              <td align="center" style='width: 10%;'>
                <%= link_to '<i class="glyphicon glyphicon-pencil"></i>'.html_safe, edit_article_path(article), class: 'btn btn-default' %>
                <%= link_to '<i class="glyphicon glyphicon-trash"></i>'.html_safe, article_path(article),
                 data: {
                    confirm: '¿Esta seguro?',
                    'confirm-button-text': 'Si',
                    'cancel-button-text': 'Cancelar'
                  },
                  method: :delete, class: 'btn btn-danger'
                 %>
              </td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h3 class='empty-article'>No tienes ningún producto todavía</h3>
  <% end %>
</div>

app/views/articles/shared/_images.html.erb
<div class="col-sm-6">
  <!-- Slider -->
  <% if @article.article_images.present? %>
    <div class="row">
      <div class="col-sm-3" id="slider-thumbs">
        <!-- Bottom switcher of slider -->
        <ul class="hide-bullets">
          <% @article.article_images.each_with_index do |image, index| %>
            <li class="col-sm-12">
              <a class="thumbnail" id="carousel-selector-<%= index %>">
                <%= image_tag image.image_file_name.url %>
              </a>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="col-sm-8">
        <div class="col-xs-12" id="slider">
          <!-- Top part of the slider -->
          <div class="row">
            <div class="col-sm-12">
              <div class="carousel slide" id="myCarousel">
                <!-- Carousel items -->
                <div class="carousel-inner">
                  <% @article.article_images.each_with_index do |image, index| %>
                    <div class="item" data-slide-number="<%= index %>">
                      <%= image_tag image.image_file_name.url %>
                    </div>
                  <% end %>
                </div>

                <!-- Carousel nav -->
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                  <span class="glyphicon glyphicon-chevron-left"></span>
                </a>

                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                  <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!--/Slider-->
    </div>
  <% else %>
    <%= image_tag 'cover.png', class: 'img-responsive' %>
  <% end %>
</div>

<script>
  $(function($) {
    $('#myCarousel').carousel({
      interval: 5000
    });

    $('#myCarousel').find('.item').first().addClass('active');

    //Handles the carousel thumbnails
    $('[id^=carousel-selector-]').click(function () {
      var id_selector = $(this).attr("id");
      try {
        var id = /-(\d+)$/.exec(id_selector)[1];
        console.log(id_selector, id);
        $('#myCarousel').carousel(parseInt(id));
      } catch (e) {
        console.log('Regex failed!', e);
      }
    });
    // When the carousel slides, auto update the text
    $('#myCarousel').on('slid.bs.carousel', function (e) {
      var id = $('.item.active').data('slide-number');
      $('#carousel-text').html($('#slide-content-'+id).html());
    });
  });
</script>

app/views/articles/shared/_preview_image_modal.html.erb
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Previsualizar</h4>
      </div>
      <div class="modal-body">
        <img src="" id="imagepreview" style="width: 100%;">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/articles/shared/_preview_modal.html.erb
<!-- Creates the bootstrap modal where the image will appear -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Terminos y Condiciones</h4>
      </div>
      <div class="modal-body">
        <p>Al ingresar información en esta plataforma estas aceptando, de manera expresa, libre y voluntaria las siguientes condiciones para el tratamiento de sus datos personales.
        Ningún tipo de información personal será vendida.</p>

        <h2>Publicación de productos.</h2>
        <p>La información requerida se utilizará para:</p>

        <ol>
          <li>Ofertar un producto como regalo o trueque  disponible para cualquier visitante de <b>llevatelo.co</b> este estará disponible hasta que se concrete la transacción.</li>
          <li>Solicitar un producto bien sea como regalo o trueque, dicha solicitud podrá ser  vista por cualquier visitante de Llevatelo.co.</li>
          <li>Compartir la oferta del producto de manera publica por email, redes sociales, u otros medios que permitan su difusión masiva.
          <li>Establecer a <b>Llevatelo.co</b>  como un canal de comunicación  entre el publicante y aquellas personas interesadas en las ofertas.</li>
        </ol>


        <h2>Que no puedes ofertar. </h2>

        <ol>
          <li>En <b>Llevatelo.co</b> no se permite la publicación de ningún tipo de animal o ser vivo.</li>
          <li>Igualmente <b>llevatelo.co</b> no permite que se publiquen artículos prohibidos por las normas leyes vigentes del país donde se haga uso de la aplicación, por lo no se hace responsable por las transacciones de aquellos productos que no cumplan con la ley.</li>
          <li> <b>Llevatelo.co</b> es una plataforma gratuita y no se permite el uso de dinero como intercambio a otros productos en la plataforma, salvo sea moneda coleccionable.</li>
        </ol>


        <h2>En General</h2>

        <p>Al navegar y registrarte a <b>Llevatelo.co</b>  reconoces y aceptas que tus datos aquí registrados podrán ser puestos a disposición del personal encargado dentro de la compañía con el fin de cumplir las  finalidades citadas.
          Además  reconoces y aceptas que te hemos informado plena y suficientemente mente acerca de tus derechos como titular de los datos registrados en <b>Llevatelo.co</b>, y declaras, reconoces y aceptas que la información suministrada de forma voluntaria, en el momento del registro,  publicación y oferta  es verídica y que no se ha omitido o adulterado ninguna información.
          <b>Llevatelo.co</b> es solo un intermediario y no participa en ninguna transacción entre usuarios, y no se hace responsable por lo aquí publicado.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>